#!/usr/bin/env python3
"""Regenerates src/com/deltapatch/launcher/TermuxFiles.java from the files in termux/ (run after editing them)."""
import os
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
d = os.path.join(root, "termux")
def esc(s):
    return "".join({"\\": "\\\\", '"': '\\"', "\n": "\\n", "\r": "", "\t": "\\t"}.get(c, c) for c in s)
out = ["package com.deltapatch.launcher;", "", "/** Generated by tools/gen_termux.py. Do not edit by hand. */",
       "final class TermuxFiles {", "    private TermuxFiles() {}", "    static final String[][] FILES = {"]
for n in sorted(os.listdir(d)):
    lines = open(os.path.join(d, n)).read().split("\n")
    out.append('        {"%s",' % n)
    for i, l in enumerate(lines):
        last = i == len(lines) - 1
        out.append('            "%s%s"%s' % (esc(l), "" if last else "\\n", "" if last else " +"))
    out.append("        },")
out += ["    };", "}"]
open(os.path.join(root, "src/com/deltapatch/launcher/TermuxFiles.java"), "w").write("\n".join(out) + "\n")
print("ok")
