package com.deltapatch.launcher;

/** Generated by tools/gen_termux.py. Do not edit by hand. */
final class TermuxFiles {
    private TermuxFiles() {}
    static final String[][] FILES = {
        {"ExportCode.csx",
            "using System;\n" +
            "using System.IO;\n" +
            "using UndertaleModLib.Models;\n" +
            "\n" +
            "// Exports every code entry as decompiled GML into the folder given by the UTMT_OUT environment variable.\n" +
            "string outDir = Environment.GetEnvironmentVariable(\"UTMT_OUT\");\n" +
            "if (string.IsNullOrEmpty(outDir)) throw new Exception(\"UTMT_OUT is not set\");\n" +
            "Directory.CreateDirectory(outDir);\n" +
            "int ok = 0, bad = 0;\n" +
            "foreach (UndertaleCode code in Data.Code)\n" +
            "{\n" +
            "    if (code.ParentEntry != null) continue;\n" +
            "    string name = code.Name.Content;\n" +
            "    string text;\n" +
            "    try { text = GetDecompiledText(code); ok++; }\n" +
            "    catch (Exception e) { text = \"// DECOMPILE FAILED: \" + e.Message; bad++; }\n" +
            "    File.WriteAllText(Path.Combine(outDir, name + \".gml\"), text);\n" +
            "}\n" +
            "Console.WriteLine(\"exported \" + ok + \" code entries, \" + bad + \" failed\");\n" +
            ""
        },
        {"dump.sh",
            "#!/data/data/com.termux/files/usr/bin/bash\n" +
            "# DeltaPatch converter - step 3: decompile the PC file and the Android file and diff them\n" +
            "set -e\n" +
            "echo \"=== DeltaPatch code dump ===\"\n" +
            "proot-distro login ubuntu --bind /storage/emulated/0:/sdcard -- bash /sdcard/DeltaPatch/termux/inner-dump.sh\n" +
            "echo \"=== dump finished: /sdcard/DeltaPatch/dump/hadrian_edits.diff ===\"\n" +
            ""
        },
        {"inner-dump.sh",
            "set -e\n" +
            "export DOTNET_ROOT=/opt/dotnet\n" +
            "export PATH=$PATH:/opt/dotnet\n" +
            "export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1\n" +
            "export DOTNET_CLI_TELEMETRY_OPTOUT=1\n" +
            "B=/sdcard/DeltaPatch\n" +
            "S=$B/pc/data.win\n" +
            "A=$B/android/chapter3.droid\n" +
            "for f in \"$S\" \"$A\"; do [ -f \"$f\" ] || { echo \"MISSING $f - use 'Export files' in the launcher first\"; exit 1; }; done\n" +
            "rm -rf $B/dump/pc $B/dump/android\n" +
            "UTMT_OUT=$B/dump/pc      dotnet /opt/utmt/UndertaleModCli.dll load \"$S\" -s $B/termux/ExportCode.csx\n" +
            "UTMT_OUT=$B/dump/android dotnet /opt/utmt/UndertaleModCli.dll load \"$A\" -s $B/termux/ExportCode.csx\n" +
            "cd $B/dump\n" +
            "diff -ru pc android > hadrian_edits.diff || true\n" +
            "ls -la hadrian_edits.diff\n" +
            "grep -c '^diff ' hadrian_edits.diff || true\n" +
            ""
        },
        {"inner-setup.sh",
            "# runs inside the Ubuntu environment (proot) - installs .NET 10 SDK and builds UndertaleModCli from source\n" +
            "set -e\n" +
            "export DEBIAN_FRONTEND=noninteractive\n" +
            "export DOTNET_ROOT=/opt/dotnet\n" +
            "export PATH=$PATH:/opt/dotnet\n" +
            "export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1\n" +
            "export DOTNET_CLI_TELEMETRY_OPTOUT=1\n" +
            "apt-get update -y\n" +
            "apt-get install -y curl git unzip ca-certificates xdelta3\n" +
            "if [ ! -x /opt/dotnet/dotnet ]; then\n" +
            "  curl -sSL https://dot.net/v1/dotnet-install.sh -o /tmp/dotnet-install.sh\n" +
            "  bash /tmp/dotnet-install.sh --channel 10.0 --install-dir /opt/dotnet\n" +
            "fi\n" +
            "dotnet --version\n" +
            "if [ ! -f /opt/utmt/UndertaleModCli.dll ]; then\n" +
            "  rm -rf /tmp/utmt-src\n" +
            "  git clone --depth 1 --recurse-submodules --shallow-submodules https://github.com/UnderminersTeam/UndertaleModTool /tmp/utmt-src\n" +
            "  cd /tmp/utmt-src\n" +
            "  dotnet publish UndertaleModCli -c Release -p:PublishSingleFile=false --self-contained false -o /opt/utmt\n" +
            "fi\n" +
            "ls /opt/utmt/UndertaleModCli.dll\n" +
            "echo \"UndertaleModCli ready.\"\n" +
            ""
        },
        {"make.sh",
            "#!/data/data/com.termux/files/usr/bin/bash\n" +
            "# DeltaPatch - make the patched game file with xdelta3 (run inside Termux, started by the launcher)\n" +
            "B=/sdcard/DeltaPatch\n" +
            "mkdir -p \"$B/out\"\n" +
            "fail() { echo \"ERROR $1\" > \"$B/out/result.txt\"; echo \"ERROR: $1\"; exit 1; }\n" +
            "echo \"RUNNING\" > \"$B/out/result.txt\"\n" +
            "if [ ! -r \"$B\" ]; then\n" +
            "  echo \"Termux needs storage access - tap Allow.\"\n" +
            "  termux-setup-storage\n" +
            "  sleep 8\n" +
            "fi\n" +
            "CH=3\n" +
            "[ -f \"$B/termux/job.conf\" ] && . \"$B/termux/job.conf\"\n" +
            "[ -f \"$B/pc/data.win\" ] || fail \"missing /sdcard/DeltaPatch/pc/data.win (use 'Copy files' first)\"\n" +
            "[ -f \"$B/pc/patch.xdelta\" ] || fail \"missing /sdcard/DeltaPatch/pc/patch.xdelta (use 'Copy files' first)\"\n" +
            "if ! command -v xdelta3 > /dev/null 2>&1; then\n" +
            "  pkg update -y\n" +
            "  pkg install -y xdelta3 || fail \"could not install xdelta3\"\n" +
            "fi\n" +
            "rm -f \"$B/out/chapter$CH.droid\"\n" +
            "xdelta3 -d -f -B 134217728 -s \"$B/pc/data.win\" \"$B/pc/patch.xdelta\" \"$B/out/chapter$CH.droid\" || fail \"xdelta3 failed: wrong PC data.win version, or not enough free space\"\n" +
            "# Android adaptation hook (added later): runs if the converter step is installed\n" +
            "if [ -f \"$B/termux/adapt.sh\" ]; then\n" +
            "  bash \"$B/termux/adapt.sh\" \"$B/out/chapter$CH.droid\" || fail \"adapt step failed\"\n" +
            "fi\n" +
            "ls -l \"$B/out/chapter$CH.droid\"\n" +
            "echo \"OK\" > \"$B/out/result.txt\"\n" +
            "echo \"Done. Go back to the launcher.\"\n" +
            ""
        },
        {"setup.sh",
            "#!/data/data/com.termux/files/usr/bin/bash\n" +
            "# DeltaPatch converter - step 1: install everything (run inside Termux, started by the launcher)\n" +
            "set -e\n" +
            "echo \"=== DeltaPatch converter setup ===\"\n" +
            "if [ ! -r /sdcard/DeltaPatch ]; then\n" +
            "  echo \"Termux has no storage access yet. Allowing it now (tap Allow)...\"\n" +
            "  termux-setup-storage || true\n" +
            "  sleep 8\n" +
            "fi\n" +
            "mkdir -p /sdcard/DeltaPatch/dump\n" +
            "pkg update -y\n" +
            "pkg install -y proot-distro curl xdelta3 unzip\n" +
            "proot-distro install ubuntu || true\n" +
            "proot-distro login ubuntu --bind /storage/emulated/0:/sdcard -- bash /sdcard/DeltaPatch/termux/inner-setup.sh\n" +
            "echo \"=== setup finished ===\"\n" +
            ""
        },
    };
}
